In [16]:
import numpy as np

arr100 = np.r_[1:200:1]
arr100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [6]:
arr_eye = np.eye(10)
arr_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
matrix3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("Last element vector", arr100[-1])
print("Last element 3x3", matrix3x3[-1,-1])

Last element vector 199
Last element 3x3 9


In [13]:
arr9 = np.array([1,2,3,4,5,6,7,8,9])
print(arr9)
print(arr9.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(arr100[arr100%2==0])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [26]:
varArr = np.array([1,2,3,'A','B', 1.23, True, 4])
type(varArr)
varArr.dtype.name
varArr.size

8

In [27]:
print("Last item: ", varArr[-1])
print("Last item: ", varArr[varArr.size-1])

Last item:  4
Last item:  4


In [33]:
A = np.arange(1,10).reshape(3,3)
B = np.arange(2,11).reshape(3,3)
print("A",A)
print("B",B)

print("A @ B", A @ B)
print("A + B", np.add(A,B))

print("CUMSUM", np.cumsum(A))
print("SUM", A.sum(), "SUM BY ROWS", A.sum(1), "CUM BY CLMNS",A.sum(0))

A [[1 2 3]
 [4 5 6]
 [7 8 9]]
B [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
A @ B [[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
A + B [[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]
CUMSUM [ 1  3  6 10 15 21 28 36 45]
SUM 45 SUM BY ROWS [ 6 15 24] CUM BY CLMNS [12 15 18]


In [38]:
A1 = np.array([4,-3,-2,2,4,3,2,-4])
# np.where(A1 > 0, "G", "L")
# if(A1 > 0):
#   A1
# else:
#   0
np.where(A1<0,0,A1)

array([4, 0, 0, 2, 4, 3, 2, 0])

In [45]:
# def abc(arg1, arg2, arg3="default", arg4=1):
#   print("XXX")

# abc(1,2)
# abc(arg2=1,arg1=2,arg3=3)

RND10 = np.random.normal(size=9).reshape(3,3);
RND10
RND100 = np.random.normal(0.5, 0.3, 100)
RND100

array([ 0.69527694,  0.34484495,  0.75121252,  0.15329111, -0.35101443,
        0.54372815,  0.28559707,  0.98480024,  0.49859764,  0.2235087 ,
        1.08604851,  0.74106068,  0.69922116,  0.22829484,  0.85525351,
        1.21420053,  0.52736786,  0.29812335,  0.88525414,  0.44048619,
        0.0116744 ,  0.526944  ,  0.36470585,  0.42932222,  0.61722291,
        0.69798382,  0.4814527 ,  0.74652426,  0.78192707,  0.71674361,
        0.59832645,  0.31869056,  0.19588382, -0.12883134,  0.71087062,
        0.51196244,  0.19251756,  0.30320201,  0.83851237, -0.06376057,
        0.27608303,  0.74473871,  0.74102181,  0.3813611 ,  0.20697314,
        0.40700605,  0.16354019,  0.46678156,  0.42744606,  0.13598823,
        0.82692261,  0.71582789,  0.50185278,  0.08693687,  0.65753587,
        0.20457872,  0.85889566,  0.84443172,  0.40889241,  0.63766151,
        0.63737804,  0.02451388,  0.87078587,  0.34829535,  0.72746918,
        0.26133447,  0.67458559,  0.63762329,  0.52132894,  0.27